language: go

os:
  - linux
  - osx

go:
  - 1.13.x
  - tip

matrix:
  allow_failures:
    - go: tip

before_install:
  - if [[  == 1.13* ]]; then go get github.com/axw/gocov/gocov github.com/modocache/gover github.com/mattn/goveralls; fi

script:
  - cd zeta && go test -v -tags ci ./...
  - if [[  == 1.13* ]]; then /Users/mantra/golang/numerati/bin/goveralls -service=travis-ci; fi

notifications:
  email:
    on_success: change
    on_failure: always
